[package]
name = "xylo-lang"
version = "0.1.0"
edition = "2021"

[dependencies]
image = "0.25.5"
nom = { version = "8.0.0", default-features = false, features = ["alloc"] }
wgpu = "24.0.1"

[features]
std = ["nom/std"]
