name: Release Binaries

on:
  push:
    tags:
      - "v*"

jobs:
  build:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            binary_name: xylo-lang
          - os: macos-latest
            binary_name: xylo-lang
          - os: windows-latest
            binary_name: xylo-lang.exe

    steps:
    - uses: actions/checkout@v2

    - name: Build
      run: cargo build --release

    - name: Create Release
      id: create_release
      uses: softprops/action-gh-release@v2
      if: github.ref_type == 'tag'
      with:
        files: |
          target/release/${{ matrix.binary_name }}
