name: Release Binaries

on:
  push:
    tags:
      - "v*"

permissions:
  contents: write

jobs:
  build:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            target: target/release/xylo-lang
            file_name: xylo_ubuntu
          - os: macos-latest
            target: target/release/xylo-lang
            file_name: xylo_macos
          - os: windows-latest
            target: target/release/xylo-lang.exe
            file_name: xylo_windows.exe

    steps:
    - uses: actions/checkout@v2

    - name: Build
      run: |
        cargo build --release
        mv ${{ matrix.target }} ${{ matrix.file_name }}

    - name: Create Release
      id: create_release
      uses: softprops/action-gh-release@v2
      if: github.ref_type == 'tag'
      with:
        files: |
          ${{ matrix.file_name }}
